default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['LF_DATABASE_DEV_NAME'] %>
  pool: 5
  username: <%= ENV['LF_DATABASE_DEV_USER'] %>
  password: <%= ENV['LF_DATABASE_DEV_PASSWORD'] %>

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['LF_DATABASE_TEST_NAME'] %>
  pool: 5
  username: <%= ENV['LF_DATABASE_TEST_USER'] %>
  password: <%= ENV['LF_DATABASE_TEST_PASSWORD'] %>

prodution:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['LF_DATABASE_PROD_NAME'] %>
  pool: 5
  username: <%= ENV['LF_DATABASE_PROD_USER'] %>
  password: <%= ENV['LF_DATABASE_PROD_PASSWORD'] %>
