# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f609f8f79cfda649514371bfd17d09e870bbccfc7f5c805c1e3d1090a0e54e19460a0788529cc9b187b0ee98898b3150529a53c3476b9467d94398da406d80

test:
  secret_key_base: aa975555c8c2a5289ae3f5b42d1b39d7317fc9a7144e216b4c17d91abac56e26629a46c722f869a5244fd602c0a4192df7f2717240f8c1732ad6c34b32e2cdec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
